# Generated by Django 4.2.6 on 2023-10-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
