# Generated by Django 4.2.6 on 2023-11-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_ticket_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Bag',
            field=models.BooleanField(blank=True, default=False, max_length=25, null=True),
        ),
    ]
