# Generated by Django 4.2.6 on 2023-11-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_remove_contact_us_name_contact_us_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='user',
        ),
    ]
