# Generated by Django 4.2.6 on 2023-11-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0018_remove_contact_us_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='firstname',
            new_name='name',
        ),
    ]
